### PR TITLE
Feat/Add simple client mode

### LINKED ISSUE #91: Support simple response handling of NeoFS API client
## Context

After neofs-sdk-go#83 `client.Client` returns result (`res`) with server status and `error`. Error carries internal client failures only, while all `res` carries any NeoFS API returns including failures. This is the most basic client interface, and all error handling logic remains on the application side. There are several client applications that combine internal errors along with server failures:

- NeoFS oracle in Neo Go lib https://github.com/nspcc-dev/neo-go/pull/2276
- NeoFS CLI https://github.com/nspcc-dev/neofs-node/pull/961
- `pool.Pool` https://github.com/nspcc-dev/neofs-sdk-go/pull/83

It would be convenient for clients of this kind (let's call them simple) to have native support for this mode of operation in NeoFS SDK.

## Possible solutions

1. Add dedicated implementation of `client.Client` interface. It can pull out status, and return failed statuses as `error` (see examples above).
2. Provide the package API to set simple mode of the client (in the constructor or at the initialization stage).

Note: 1 and 2 should be kept in sync with https://github.com/nspcc-dev/neofs-sdk-go/issues/89.

### PR DESCRIPTION
**Pull request by carpawell**
Closes #91.

### CODE REVIEW

**Review by cthulhu-rider — APPROVED** [review]
Using the feature by `pool.Pool` in a separate PR?

**Comment by carpawell** [comment]
> Using the feature by pool.Pool in a separate PR?

not sure how and when should it be added to `pool` since the client default behavior (without the new option) has not been changed

/cc @alexvanin, @KirillovDenis

**Comment by KirillovDenis** [comment]
> > Using the feature by pool.Pool in a separate PR?
> 
> not sure how and when should it be added to `pool` since the client default behavior (without the new option) has not been changed
> 
> /cc @alexvanin, @KirillovDenis


The default behavior should be opposite as I understand https://github.com/nspcc-dev/neofs-sdk-go/issues/91#issuecomment-977678938

**Comment by carpawell** [comment]
> The default behavior should be opposite as I understand #91 (comment)

After internal discussion, we have decided that it would be better to have errors as part of results/statuses by default. So I meant that this PR does not change behavior in any old code and I can not answer @cthulhu-rider's question about `pool` since I do not know when it was planned to use "simple" client and if `pool` needs it at all.

**Comment by alexvanin** [comment]
> not sure how and when should it be added to pool since the client default behavior (without the new option) has not been changed

Use new client option in [client builder](https://github.com/nspcc-dev/neofs-sdk-go/blob/13d72efd60790e4fff345f8d81c9c0ac7f6f2754/pool/pool.go#L277) and remove repeating 
```go
	if err == nil {
		// reflect status failures in err
		err = apistatus.ErrFromStatus(res.Status())
	}
```
constructions. I propose to do that in this PR with one more commit.

> After internal discussion, we have decided that it would be better to have errors as part of results/statuses by default.

Indeed, majority of opinions went this way. I guess we can discuss such details here in comments later on, so everyone will be synced.

**Review by KirillovDenis — APPROVED** [review]

**Pull request merged**
