### PR TITLE
Update session control inside pool

### LINKED ISSUE #499: PutObjectRetention and other s3 calls fails with session token not found
Test test_s3_object_locking
image

https://http.fs.neo.org/HXSaMJXk2g8C14ht8HSi7BBaiYZ1HeWh2xnWPGQCg4H6/608-1692970274/index.html#suites/c492cece70fc6a94e2e9567b84ff6c83/42c74ec586b09660/

```
2023-08-25T14:49:58.034Z	error	handler/util.go:29	call method	{"status": 500, "request_id": "703cf3b3-f7a7-4ea0-813a-bf71c3f0dba5", "method": "PutObjectRetention", "bucket": "8340980b-cec5-4e66-941d-b999ceab95a7", "object": "e1b3c4b7-81dd-4cf6-9b26-648b0b1ce59a", "description": "couldn't put legal hold", "error": "save object via connection pool: init writing on API client: client failure: status: code = 4096 message = session token not found"}
2023-08-25T14:49:58.683Z	error	handler/util.go:29	call method	{"status": 500, "request_id": "bfe06cd4-aade-4b58-8398-545271cba479", "method": "PutObjectRetention", "bucket": "8340980b-cec5-4e66-941d-b999ceab95a7", "object": "e1b3c4b7-81dd-4cf6-9b26-648b0b1ce59a", "description": "couldn't put legal hold", "error": "save object via connection pool: init writing on API client: client failure: status: code = 4096 message = session token not found"}
```

Reproduced only in CI runs, didn't manage to reproduce this failure manually. Looks like a strange flipper

[c9d33826aed6cc64.zip](https://github.com/nspcc-dev/neofs-node/files/12442556/c9d33826aed6cc64.zip)

### PR DESCRIPTION
**Pull request by smallhive**
closes #499

### CODE REVIEW

**Comment by roman-khimov** [comment]
Yeah, this needs a real explanation of the mechanics behind it and intended consequences.

**Comment by smallhive** [comment]
Extended commit message text. Any suggestions are welcome

**Review by AliceInHunterland — APPROVED** [review]
LGTM

**Review by roman-khimov — APPROVED** [review]

**Review by carpawell — APPROVED** [review]
> It may happen because epoch changed, but pool
not updated yet.

How often the `Pool` is updated? Can it be less than once an epoch?

**Comment by roman-khimov** [comment]
> Can it be less than once an epoch?

Technically can. Practically highly unlikely.

**Pull request merged**
