### PR TITLE
[#362] pool: Don't use default session token for read

### LINKED ISSUE #362: pool: Do not use session tokens for read operations
NeoFS CLI does not generate session tokens for read operations. There is no need for pool to behave differently.

### PR DESCRIPTION
**Pull request by KirillovDenis**
close #362 
Signed-off-by: Denis Kirillov <denis@nspcc.ru>

### CODE REVIEW

**Review by masterSplinter01 — APPROVED** [review]

**Comment by alexvanin** [comment]
Let's run some tests on this branch first when we'll have time (optimization, not a but).

**Review by carpawell — APPROVED** [review]

**Comment by cthulhu-rider** [comment]
> Let's run some tests on this branch first when we'll have time (optimization, not a bug).

Were they OK?

**Comment by KirillovDenis** [comment]
> Were they OK?

We don't have results yet

**Comment by roman-khimov** [comment]
@cthulhu-rider, do we need any additional tests here?

**Pull request merged**
